#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

config:
  name: v3

spring:
  main:
    allow-circular-references: true
    security:
      oauth2:
        client:
          registration:
            keycloak:
              client-id: test_client
              client-secret: V6YhT2TH5UsT5b7dpR15jX9OksE8HtZM
              scope: openid
              authorization-grant-type: client_credentials
              token-uri: http://localhost:8080/realms/test_realm/protocol/openid-connect/token
          provider:
            keycloak:
              issuer-uri: http://localhost:8080/realms/test_realm
